[package]
name = "fluent4rs"
version = "0.1.10"
edition = "2021"

[dependencies]
pom = "3.4.0"
thiserror = "2.0.11"

[dev-dependencies]
pretty_assertions = "1.4.1"

[features]
default = ["hash"]
hash = []
