[package]
name = "fluent4rs"
version = "0.1.9"
edition = "2021"

[dependencies]
pom = { git = "https://github.com/nigeleke/pom.git", features = ["trace"] }
thiserror = "2.0.11"
serde = { version = "1.0.217", features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = "1.4.1"

[features]
default = []
hash = []
serde = ["dep:serde"]
