# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on:
    push:
        branches-ignore:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Compile
              run: |
                  cargo build --no-default-features --verbose
                  cargo build --features=allow-junk --verbose
                  cargo build --features=hash --verbose
                  cargo build --features=serde --verbose
                  cargo build --features=trace --verbose
                  cargo build --features=walker --verbose
                  cargo build --all-features --verbose

            - name: Lint
              run: |
                  cargo clippy --no-default-features
                  cargo clippy --features=allow-junk
                  cargo clippy --features=hash
                  cargo clippy --features=serde
                  cargo clippy --features=trace
                  cargo clippy --features=walker
                  cargo clippy --all-features

            - name: Test
              run: |
                  cargo test --no-default-features --verbose -- --show-output
                  cargo test --features=allow-junk --verbose -- --show-output
                  cargo test --features=hash --verbose -- --show-output
                  cargo test --features=serde --verbose -- --show-output
                  cargo test --features=trace --verbose -- --show-output
                  cargo test --features=walker --verbose -- --show-output
                  cargo test --all-features --verbose -- --show-output
