# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on:
    push:
        branches-ignore:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Compile
              run: |
                  cargo build --no-default-features
                  cargo build --features=hash
                  cargo build --features=serde
                  cargo build --features=trace
                  cargo build --features=walker
                  cargo build --features=walker_depth
                  cargo build --all-features

            - name: Lint
              run: |
                  cargo clippy --no-default-features
                  cargo clippy --features=hash
                  cargo clippy --features=serde
                  cargo clippy --features=trace
                  cargo clippy --features=walker
                  cargo clippy --features=walker_depth
                  cargo clippy --all-features

            - name: Test
              run: |
                  cargo test --no-default-features
                  cargo test --features=hash
                  cargo test --features=serde
                  cargo test --features=trace
                  cargo test --features=walker
                  cargo test --features=walker_depth
                  cargo test --all-features
