# Run publish-cycle on main commits.
#
# Publish cycle comprises:
# - publish site, coverage reports and API documentation to https://nigeleke.github.io
#
name: Github Pages Publish

on:
    workflow_run:
        workflows: ["Acceptance Cycle"]
        branches: [main]
        types:
            - completed

jobs:
    publish:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build Site
              run: |
                  cargo doc --no-deps --all-features
                  rustup toolchain install nightly
                  rustup component add llvm-tools-preview --toolchain nightly
                  cargo install cargo-llvm-cov
                  mkdir -p docs0/doc
                  echo "**** 1"
                  cat README.md | grep svg
                  cp README.md docs0/
                  cp doc/*.svg docs0/doc/
                  cargo llvm-cov --all-features --cobertura --output-path=cobertura.xml

            - name: Publish to Codecov
              uses: codecov/codecov-action@v5
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            - name: Build App
              run: |
                  rm codecov*
                  cargo build --release

            - name: Publish App & Documentation
              run: |
                  git config --global user.email "nigeleke@users.noreply.github.com"
                  git config --global user.name "Nigel Eke"
                  export VERSION=$(git describe --abbrev=0 --tags)
                  git checkout gh-pages
                  rm -rf docs
                  mv docs0 docs
                  echo "**** 2a"
                  cat docs/README.md | grep svg
                  echo "**** 2b"
                  ls docs
                  echo "**** 2c"
                  ls docs/doc
                  git add .
                  git commit -m "Release $VERSION"
                  git push
