name: Cargo Publish

on:
    workflow_run:
        workflows: ["Acceptance Cycle"]
        branches: [main]
        types:
            - completed

env:
    CARGO_TERM_COLOR: always

jobs:
    publish:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Publish to crate.io
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                  echo "***** A"
                  cat README.md | grep svg
                  ls
                  cargo publish --all-features
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
