name: Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    tags:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: nigeleke/github/.github/actions/cargo-verify-version-vs-tag@main

    rust-publish:
        needs: [tags]
        uses: nigeleke/github/.github/workflows/rust-publish.yml@main
        with:
            matrix: |
                [
                  {"cargo-extra-args": "--features parser-chumsky,walker,hash,serde,trace"}
                ]
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    crates-io-publish:
        needs: [rust-publish]
        uses: nigeleke/github/.github/workflows/crates-io-publish.yml@main
        with:
            matrix: |
                [
                  {"cargo-extra-args": "--features parser-chumsky,walker,hash,serde,trace"}
                ]
        secrets:
            CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
